# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: trade_command.proto
# plugin: python-betterproto
from dataclasses import dataclass
from datetime import datetime
from typing import AsyncGenerator, List, Optional

import betterproto
import grpclib


class StrategyType(betterproto.Enum):
    STRATEGY_UNSPECIFIED = 0
    STRATEGY_FUNDING_RATE_ARB = 1
    STRATEGY_MEV_LIQUIDATION = 2
    STRATEGY_STAT_ARB_CROSSVENUE = 3
    STRATEGY_MEAN_REVERSION_L2 = 4


class AssetClass(betterproto.Enum):
    ASSET_CLASS_UNSPECIFIED = 0
    ASSET_CLASS_SPOT = 1
    ASSET_CLASS_PERP = 2
    ASSET_CLASS_DATED_FUT = 3
    ASSET_CLASS_OPTION = 4


class OrderSide(betterproto.Enum):
    ORDER_SIDE_UNSPECIFIED = 0
    ORDER_SIDE_BUY = 1
    ORDER_SIDE_SELL = 2


class ExecutionAlgo(betterproto.Enum):
    EXECUTION_ALGO_UNSPECIFIED = 0
    EXECUTION_ALGO_TWAP = 1
    EXECUTION_ALGO_VWAP = 2
    EXECUTION_ALGO_ICEBERG = 3
    EXECUTION_ALGO_AGGRESSIVE = 4
    EXECUTION_ALGO_PASSIVE = 5


class RiskGateCode(betterproto.Enum):
    RISK_GATE_UNSPECIFIED = 0
    RISK_GATE_ACCEPTED = 1
    RISK_GATE_REJECTED_MAX_DRAWDOWN = 2
    RISK_GATE_REJECTED_VAR_BREACH = 3
    RISK_GATE_REJECTED_GARCH_VOLATILITY = 4
    RISK_GATE_REJECTED_NOTIONAL_LIMIT = 5
    RISK_GATE_REJECTED_LEVERAGE_LIMIT = 6
    RISK_GATE_REJECTED_CONCENTRATION = 7
    RISK_GATE_REJECTED_SIGNAL_STALE = 8
    RISK_GATE_REJECTED_INSUFFICIENT_LIQ = 9
    RISK_GATE_EXECUTION_ERROR = 10


@dataclass
class FixedDecimal(betterproto.Message):
    raw_units: int = betterproto.int64_field(1)
    scale: int = betterproto.uint32_field(2)


@dataclass
class AssetIdentifier(betterproto.Message):
    base_asset: str = betterproto.string_field(1)
    quote_asset: str = betterproto.string_field(2)
    asset_class: "AssetClass" = betterproto.enum_field(3)
    venue_id: str = betterproto.string_field(4)
    instrument: str = betterproto.string_field(5)


@dataclass
class SignalInvalidationThresholds(betterproto.Message):
    signal_ttl_ms: int = betterproto.uint64_field(1)
    max_price_drift_bps: int = betterproto.uint32_field(2)
    min_funding_spread_bps_e2: int = betterproto.int32_field(3)
    min_fill_probability: "FixedDecimal" = betterproto.message_field(4)
    min_available_liquidity: "FixedDecimal" = betterproto.message_field(5)


@dataclass
class TradeRequest(betterproto.Message):
    request_id: str = betterproto.string_field(1)
    originating_agent_id: str = betterproto.string_field(2)
    signal_detected_at: datetime = betterproto.message_field(3)
    asset: "AssetIdentifier" = betterproto.message_field(4)
    side: "OrderSide" = betterproto.enum_field(5)
    notional_value: "FixedDecimal" = betterproto.message_field(6)
    leverage_ratio: "FixedDecimal" = betterproto.message_field(7)
    execution_algo: "ExecutionAlgo" = betterproto.enum_field(8)
    slippage_bps_limit: int = betterproto.uint32_field(9)
    execution_ttl_ms: int = betterproto.uint64_field(10)
    strategy_type: "StrategyType" = betterproto.enum_field(11)
    strategy_version: str = betterproto.string_field(12)
    signal_embedding: bytes = betterproto.bytes_field(13)
    signal_confidence: "FixedDecimal" = betterproto.message_field(14)
    invalidation: "SignalInvalidationThresholds" = betterproto.message_field(15)


@dataclass
class TradeResponse(betterproto.Message):
    request_id: str = betterproto.string_field(1)
    execution_id: str = betterproto.string_field(2)
    received_at: datetime = betterproto.message_field(3)
    responded_at: datetime = betterproto.message_field(4)
    risk_gate_code: "RiskGateCode" = betterproto.enum_field(5)
    filled_notional: "FixedDecimal" = betterproto.message_field(6)
    average_fill_price: "FixedDecimal" = betterproto.message_field(7)
    realized_slippage: "FixedDecimal" = betterproto.message_field(8)
    risk_snapshot: "RiskState" = betterproto.message_field(9)
    rejection_detail: str = betterproto.string_field(10)
    exchange_order_ids: List[str] = betterproto.string_field(11)
    commission_paid: "FixedDecimal" = betterproto.message_field(12)


@dataclass
class RiskState(betterproto.Message):
    portfolio_drawdown_pct: "FixedDecimal" = betterproto.message_field(1)
    var_1d_99_pct: "FixedDecimal" = betterproto.message_field(2)
    garch_sigma_sq: "FixedDecimal" = betterproto.message_field(3)
    gross_exposure: "FixedDecimal" = betterproto.message_field(4)
    net_exposure: "FixedDecimal" = betterproto.message_field(5)
    open_position_count: int = betterproto.uint32_field(6)
    evaluated_at_ns: int = betterproto.uint64_field(7)


@dataclass
class RiskSubscriptionRequest(betterproto.Message):
    agent_id: str = betterproto.string_field(1)
    throttle_interval_ms: int = betterproto.uint32_field(2)


class TradeCommandServiceStub(betterproto.ServiceStub):
    async def submit_trade_command(
        self,
        *,
        request_id: str = "",
        originating_agent_id: str = "",
        signal_detected_at: Optional[datetime] = None,
        asset: Optional["AssetIdentifier"] = None,
        side: "OrderSide" = 0,
        notional_value: Optional["FixedDecimal"] = None,
        leverage_ratio: Optional["FixedDecimal"] = None,
        execution_algo: "ExecutionAlgo" = 0,
        slippage_bps_limit: int = 0,
        execution_ttl_ms: int = 0,
        strategy_type: "StrategyType" = 0,
        strategy_version: str = "",
        signal_embedding: bytes = b"",
        signal_confidence: Optional["FixedDecimal"] = None,
        invalidation: Optional["SignalInvalidationThresholds"] = None,
    ) -> TradeResponse:
        request = TradeRequest()
        request.request_id = request_id
        request.originating_agent_id = originating_agent_id
        if signal_detected_at is not None:
            request.signal_detected_at = signal_detected_at
        if asset is not None:
            request.asset = asset
        request.side = side
        if notional_value is not None:
            request.notional_value = notional_value
        if leverage_ratio is not None:
            request.leverage_ratio = leverage_ratio
        request.execution_algo = execution_algo
        request.slippage_bps_limit = slippage_bps_limit
        request.execution_ttl_ms = execution_ttl_ms
        request.strategy_type = strategy_type
        request.strategy_version = strategy_version
        request.signal_embedding = signal_embedding
        if signal_confidence is not None:
            request.signal_confidence = signal_confidence
        if invalidation is not None:
            request.invalidation = invalidation

        return await self._unary_unary(
            "/tradecommand.v1.TradeCommandService/SubmitTradeCommand",
            request,
            TradeResponse,
        )

    async def stream_risk_state(
        self, *, agent_id: str = "", throttle_interval_ms: int = 0
    ) -> AsyncGenerator[RiskState, None]:
        request = RiskSubscriptionRequest()
        request.agent_id = agent_id
        request.throttle_interval_ms = throttle_interval_ms

        async for response in self._unary_stream(
            "/tradecommand.v1.TradeCommandService/StreamRiskState",
            request,
            RiskState,
        ):
            yield response
